#!/usr/bin/env bash
# Display information about subdomains

get_info () {
    dig "${2}.${1}" +noall +answer | awk -v subdomain="${2}" '{print "The subdomain " subdomain " is a " $4 " record and points to " $5}'
}

subs=("www" "lb-01" "web-01" "web-02")
if [ "$#" -eq 1 ]; then
    for sub in "${subs[@]}"; do
        get_info "$1" "$sub"
    done
elif [ "$#" -eq 2 ]; then
    get_info "$1" "$2"
fi
