#!/bin/bash
# Configure `Nginx` web server so that each server contains its hostname in its response header
sudo apt-get update
sudo apt-get install nginx -y

sudo sed -i "/server_name _;/a \ \n\tadd_header X-Served-By \"$(hostname)\";" /etc/nginx/sites-available/default

sudo service nginx restart
