#!/usr/bin/env bash
# Restart Nginx to make it liaten on port 80 after installation

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default 
sudo service nginx restart > /dev/null
