#!/usr/bin/env bash
# Make the fix simple and short
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart > /dev/null
kill -9 "$(cat /var/run/nginx.pid)"
