#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd.
# The script only dispay username, user id and Home directory path for the user.

while read -r line; do
	if [ "$line" ]; then
		echo "$line" | cut -d':' -f1,3,6
	fi
done < "/etc/passwd"
